FROM amazoncorretto:19

#
# Download the ADOT agent
#
RUN curl -LJO -o aws-opentelemetry-agent.jar github.com/aws-observability/aws-otel-java-instrumentation/releases/download/v1.20.0/aws-opentelemetry-agent.jar

COPY ./target/demonstrationApp-1.0.0.jar demonstrationApp.jar
COPY open-telemetry-java-agent.properties open-telemetry-java-agent.properties

ENTRYPOINT ["java","-javaagent:aws-opentelemetry-agent.jar","-Dotel.javaagent.configuration-file=open-telemetry-java-agent.properties", "-jar","/demonstrationApp.jar"]