version: '3.8'
services:
  collector:
    image: amazon/aws-otel-collector
    ports:
      - "4317:4317"
      - "55680:55680"
      - "8889:8888"
    environment:
      - AWS_REGION=us-east-1
      - AWS_PROFILE=default
    volumes:
      - ~/.aws:/root/.aws
  demonstrationapp:
    image: demoapp/demo-app:v1.0.0
    ports:
      - "8080:8080"
    environment:
      - AWS_REGION=us-east-1
      - AWS_PROFILE=default
      - OTEL_JAVAAGENT_CONFIGURATION_FILE=open-telemetry-java-agent.properties
    volumes:
      - ~/.aws:/root/.aws
