FROM amazoncorretto:19
VOLUME /tmp

COPY ./target/aws-opentelemetry-agent-1.20.0.jar aws-opentelemetry-agent-1.20.0.jar
COPY ./target/demonstrationApp-0.0.1-SNAPSHOT.jar demonstrationApp.jar
COPY open-telemetry-java-agent.properties open-telemetry-java-agent.properties

ENTRYPOINT ["java","-javaagent:aws-opentelemetry-agent-1.20.0.jar","-jar","/demonstrationApp.jar"]